Hotfix/7/SC-5287
hpi-schul-cloud/schulcloud-client pull request #2128
Opened 2020-08-22 19:51 UTC by dominikglandorf

# Description
Due to changes in login logic, OAuth2 login challenges were not considered when redirecting after login.

## Links to Tickets or other pull requests
-

## Changes
Check for login_challenge in session when redirecting.

## Data Security <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>
Nothing new

## Deployment
Nothing new

## New Repos, NPM packages or vendor scripts
Nothing new

## Screenshots of UI changes
No change

## Approval for review
- [ x ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-08-24 07:12 UTC, janrenz requested changes

2020-08-24 07:12 UTC, janrenz commented on controllers/login.js
> -	const validRedirect = redirectHelper.getValidRedirect(redirect);
is this removed on purpose? (i know its not because we just had a call, so this is just a reminder)

2020-09-22 09:19 UTC, janrenz commented on config/http-headers.js
> +		'X-Frame-Options': 'allow-from https://acc.bettermarks.com/',
Please check with DevOps if this should be set on the instances or here in code

2020-09-22 09:23 UTC, Parnswir requested changes

2020-09-22 09:23 UTC, Parnswir commented on config/http-headers.js
> +				defaultSrc: 'https://oauth.hotfix7.schul-cloud.dev https://nexboard.nexenio.com https://www.geogebra.org https://lti.tools https://codeocean.openhpi.de https://acc.bettermarks.com https://moodle.
I don't think it's a good idea to merge this as-is. Maybe this should read this from the configuration?

2020-10-20 13:50 UTC, dominikglandorf commented
This was caused by another error in the login logic.

2020-10-20 13:50 UTC, closed without merging