SC-6261 BRB Landing Page changes
hpi-schul-cloud/schulcloud-client pull request #2144
Opened 2020-08-31 10:24 UTC by pkleybolte

# Description

## Links to Tickets or other pull requests
https://ticketsystem.schul-cloud.org/browse/SC-6261

## Changes

## Data Security <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-09-01 07:21 UTC, alriese requested changes

2020-09-01 07:21 UTC, alriese commented on theme/brb/views/authentication/home.hbs
> +						Anschließend erhalten alle Schüler:innen von iIhrer Schule einen Registrierungslink oder Login-Daten für die erstmalige Anmeldung in der Schul-Cloud Brandenburg. Bei Fragen zur erstmaligen Anme
```suggestion
						Anschließend erhalten alle Schüler:innen von ihrer Schule einen Registrierungslink oder Login-Daten für die erstmalige Anmeldung in der Schul-Cloud Brandenburg. Bei Fragen zur erstmaligen Anmeldung wenden sich Schüler:innen und Eltern bitte an den technischen Leiter ihrer Schule bzw. an die jeweilige Klassenlehrerin oder den jeweiligen Klassenlehrer.
```

2020-09-01 07:21 UTC, alriese commented on theme/brb/views/authentication/home.hbs
> +                    <p>"Das Lernen mit digitalen Medien ist die Herausforderung mit der größten Dynamik. Dazu braucht es eine leistungsfähige, digitale Infrastruktur. Zu den wichtigsten Vorhaben gehö
Both options are valid, but at least the Duden recommends "sodass" (https://www.duden.de/rechtschreibung/sodass)

```suggestion
                    <p>"Das Lernen mit digitalen Medien ist die Herausforderung mit der größten Dynamik. Dazu braucht es eine leistungsfähige, digitale Infrastruktur. Zu den wichtigsten Vorhaben gehört die am Hasso-Plattner-Institut (HPI) entwickelte Schul-Cloud Brandenburg. Sie soll die Schulen des Landes vernetzen, sodass Lehrkräfte, Schülerinnen und Schüler jederzeit und überall Zugang zu Lern- und Lehrmaterialien haben. Die professionelle zentrale Wartung für alle Schulen verringert deutlich den Verwaltungs- und Betreuungsaufwand. Wir versprechen uns von der Schul-Cloud Brandenburg einen deutlichen Schub in der digitalen Bildung und freuen uns auf den Start des Projekts.“ - Bildungsministerin Britta Ernst bei der Eröffnungsveranstaltung am 2. Mai 2019.</p>
```

2020-09-01 07:21 UTC, alriese commented on theme/brb/views/authentication/home.hbs
> +                    <p>"Das Lernen mit digitalen Medien ist die Herausforderung mit der größten Dynamik. Dazu braucht es eine leistungsfähige, digitale Infrastruktur. Zu den wichtigsten Vorhaben gehö
Fix quotation marks
```suggestion
                    <p>„Das Lernen mit digitalen Medien ist die Herausforderung mit der größten Dynamik. Dazu braucht es eine leistungsfähige, digitale Infrastruktur. Zu den wichtigsten Vorhaben gehört die am Hasso-Plattner-Institut (HPI) entwickelte Schul-Cloud Brandenburg. Sie soll die Schulen des Landes vernetzen, so dass Lehrkräfte, Schülerinnen und Schüler jederzeit und überall Zugang zu Lern- und Lehrmaterialien haben. Die professionelle zentrale Wartung für alle Schulen verringert deutlich den Verwaltungs- und Betreuungsaufwand. Wir versprechen uns von der Schul-Cloud Brandenburg einen deutlichen Schub in der digitalen Bildung und freuen uns auf den Start des Projekts.“ - Bildungsministerin Britta Ernst bei der Eröffnungsveranstaltung am 2. Mai 2019.</p>
```

2020-09-02 11:37 UTC, CeEv approved these changes

2020-09-02 11:39 UTC, CeEv approved these changes

2020-09-03 06:50 UTC, merged