SC-6566: i18n some more missing keys
hpi-schul-cloud/schulcloud-client pull request #2162
Opened 2020-09-02 13:32 UTC by Tratori

https://ticketsystem.schul-cloud.org/browse/SC-6566

2020-09-03 07:13 UTC, ABialoskorski commented on locales/de.json
> +				"myPersonalFiles" : "Meine persönlichen Dateien",
duplicate

2020-09-03 07:14 UTC, ABialoskorski commented on locales/de.json
> +				"mySharedFiles" : "Mit mir geteilte Dateien",
duplicate

2020-09-03 07:17 UTC, ABialoskorski approved these changes
delete duplicates, I have found two, mocha test did not

2020-09-04 10:25 UTC, Tratori commented
> delete duplicates, I have found two, mocha test did not

Mocha Test doesnt look for duplicates between two different "types" of keys, here *.label.* and *.headline.*   ...
I think this is kind of a design flaw with our naming schema, as it leads to lots of duplicates

2020-09-10 12:50 UTC, ABialoskorski requested changes
as the requirements changed, please add english translations also :)

2020-09-15 07:37 UTC, ABialoskorski approved these changes

2020-09-17 11:57 UTC, dominikbruechner approved these changes

2020-09-17 11:57 UTC, merged