SC-6545 – Shorten button text and add download icon
hpi-schul-cloud/schulcloud-client pull request #2163
Opened 2020-09-02 14:56 UTC by monaweitzenberg

# Description

## Links to Tickets or other pull requests
https://ticketsystem.schul-cloud.org/browse/SC-6545

## Changes
updatet Button "
the button "Alle Dateien unbewerteter Hausaufgaben herunterladen" is shown
change the looooooooong text into  "Download-icon Unbewertete Hausaufgaben"

## Data Security <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-09-03 08:44 UTC, ABialoskorski approved these changes

2020-09-03 08:46 UTC, DanielRieckhof approved these changes

2020-09-03 08:46 UTC, DanielRieckhof commented on views/homework/components/bulk-grading.hbs
> +			<i class="fa fa-cloud-download"></i>
Maybe lint will complain on missing spaces/tabs

2020-09-03 08:56 UTC, seulki-lee-cloud requested changes
Compared to the suggestion image from the ticket (https://ticketsystem.schul-cloud.org/browse/SC-6545).
The color of the icon and text in the button is so light grey. It looks disabled button.
Please check the mona's suggestion image again, and use the right dark grey color.
Thank you :)

2020-09-04 08:22 UTC, seulki-lee-cloud reviewed
Thank you

2020-09-04 08:24 UTC, seulki-lee-cloud commented
thank you

2020-09-04 08:28 UTC, seulki-lee-cloud approved these changes
Thank you

2020-09-04 09:01 UTC, merged