SC-6715 Inform users about Rocket-Chat deprecation
hpi-schul-cloud/schulcloud-client pull request #2201
Opened 2020-09-16 11:56 UTC by alriese

# Description

## Links to Tickets or other pull requests

- https://ticketsystem.schul-cloud.org/browse/SC-6715

## Changes

## Data Security <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-09-17 09:28 UTC, Metauriel requested changes

2020-09-17 09:28 UTC, Metauriel commented on locales/de.json
> +			"rocketChatDeprecation": "Die Chat-Funktion im Teams-Bereich wird am DD/MM/JJJJ automatisch abgeschaltet und die dazugehörigen Inhalte gelöscht. Bitte sorge dafür, dass du wichtige Inhalte kopiers
mir wird aus dem Text nicht klar dass es um den alten Chat geht und nicht den neuen, und der neue erhalten bleibt und den alten ablöst

2020-09-21 08:56 UTC, Metauriel requested changes

2020-09-21 08:56 UTC, Metauriel commented on locales/de.json
> +					"rocketChatDeprecated": "Rocketchat wird nicht mehr unterstützt, und am {{date}} automatisch abgeschaltet."
hier würde der text von oben auch gut passen
Die alte Chat-Funktion im Teams-Bereich wird am {{date}} automatisch deaktiviert. Du kannst keine Änderungen mehr vornehmen."

2020-09-21 08:56 UTC, Metauriel commented on views/administration/school.hbs
> +									/>
!

2020-09-21 08:56 UTC, Metauriel commented on views/administration/school.hbs
> +										This is a info alert—check it out!
this doesnt seem to belong

2020-09-21 09:35 UTC, Metauriel approved these changes

2020-09-21 10:21 UTC, monaweitzenberg approved these changes

2020-09-21 17:31 UTC, merged