SC-6391 Bugfix mobile header menu
hpi-schul-cloud/schulcloud-client pull request #2221
Opened 2020-09-23 14:57 UTC by abralurrahman

# Description

## Links to Tickets or other pull requests

- https://ticketsystem.hpi-schul-cloud.org/browse/SC-6391

## Changes

## Data Security <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes
<img width="359" alt="Screenshot 2020-08-26 at 12 11 48" src="https://user-images.githubusercontent.com/59754949/94030222-db699f00-fdbd-11ea-930d-4bead83543cb.png">

## Approval for review
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-09-28 09:30 UTC, seulki-lee-cloud commented
could you please share with me fixed version? as screenshot?

2020-09-29 07:20 UTC, monaweitzenberg requested changes
![image](https://user-images.githubusercontent.com/63390574/94525901-0b3cfa80-0235-11eb-9d7c-e8ba52d44bcd.png)
iPhone5 seems not working, please check

2020-09-29 07:24 UTC, ABialoskorski commented
> iPhone5 seems not working, please check

it happens sometimes when You change device in chrome (inspect mode), try some other devices and get back to iphone 5, sometimes it needs few tries to work.

2020-09-29 07:25 UTC, ABialoskorski commented on static/styles/homepage/homepage.scss
> +
please delete this change here

2020-09-29 07:30 UTC, monaweitzenberg approved these changes
test again in firefox. went well. good job!!! thx :)

2020-09-29 09:22 UTC, ABialoskorski approved these changes

2020-09-30 14:03 UTC, mwolowyk-cap approved these changes

2020-10-01 10:52 UTC, merged