SC-6927 Fix Admins can delete teachers
hpi-schul-cloud/schulcloud-client pull request #2226
Opened 2020-09-28 09:34 UTC by pkleybolte

# Description

## Links to Tickets or other pull requests
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6927

## Changes

## Data Security <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-09-28 09:39 UTC, janrenz approved these changes

2020-09-28 09:53 UTC, Parnswir approved these changes

2020-09-28 11:17 UTC, mwolowyk-cap submitted a review, later dismissed

2020-09-28 16:16 UTC, CeEv approved these changes

2020-09-28 16:16 UTC, CeEv requested changes
Please change all to 25.0.2.

2020-09-29 07:52 UTC, CeEv approved these changes

2020-09-29 09:33 UTC, sarahschaefer approved these changes

2020-09-29 09:34 UTC, merged