SC-7040 - international landing page
hpi-schul-cloud/schulcloud-client pull request #2248
Opened 2020-10-06 14:42 UTC by ABialoskorski

# Description
landing page for international theme
## Links to Tickets or other pull requests

- https://ticketsystem.schul-cloud.org/browse/SC-7040

## Changes
added home.hbs file for international theme, to be ready to fetch content from ghost

## Screenshots of UI changes
![image](https://user-images.githubusercontent.com/40116220/95216822-cbf14980-07f2-11eb-9235-9abcddc0b529.png)

2020-10-13 14:23 UTC, janrenz requested changes
Have you checked if removal of the class breaks the SC Homepage?

2020-10-14 13:05 UTC, ABialoskorski commented
> Have you checked if removal of the class breaks the SC Homepage?

yes, I have checked, css works properly also without a class

2020-10-14 20:20 UTC, janrenz approved these changes

2020-10-21 05:14 UTC, DanielRieckhof approved these changes

2020-10-22 08:23 UTC, sarahschaefer approved these changes

2020-10-22 09:39 UTC, merged