Hotfix/1/sc 2710 custom timezone
hpi-schul-cloud/schulcloud-client pull request #2269
Opened 2020-10-16 14:51 UTC by mwolowyk-cap

# Description
enable timezones in client

## Links to Tickets or other pull requests
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/1741
- https://ticketsystem.schul-cloud.org/browse/SC-2710

## Changes

## Data Security <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts
"@fullcalendar/moment": "^4.4.2",
"@fullcalendar/moment-timezone": "^4.4.2",
"moment-timezone": "^0.5.31",

## Screenshots of UI changes

![image](https://user-images.githubusercontent.com/65842673/95051816-2ce32980-06ee-11eb-98f5-4309279c3d87.png)
![image](https://user-images.githubusercontent.com/65842673/95051826-3371a100-06ee-11eb-84c0-b4491814823a.png)
![image](https://user-images.githubusercontent.com/65842673/95051838-38ceeb80-06ee-11eb-8467-92c3e9c2869a.png)
![image](https://user-images.githubusercontent.com/65842673/95051856-3f5d6300-06ee-11eb-8851-18d9d3317215.png)

## Date Format 'EN'
![image](https://user-images.githubusercontent.com/64189574/95878728-d45afe80-0d75-11eb-873d-ecad57f27064.png)
![image](https://user-images.githubusercontent.com/64189574/95882697-4a616480-0d7a-11eb-8ca6-7e8f6726a044.png)

2020-10-28 06:03 UTC, CeEv requested changes

2020-10-28 06:03 UTC, CeEv commented on app.js
> +		// TODO: set secure after fixed in develop
Is it fixed?

2020-10-28 11:08 UTC, DanielRieckhof commented on views/homework/edit.hbs
> +                    {{> "lib/forms/form-datetime-input" label=($t "homework.global.label.visibleAndEditableForStudentsFrom") id="availableDate" value=assignment.availableDate class="input-group mb-3"
Is there another way to include partials?

2020-10-28 14:10 UTC, haniapalac commented on views/homework/edit.hbs
> +                    {{> "lib/forms/form-datetime-input" label=($t "homework.global.label.visibleAndEditableForStudentsFrom") id="availableDate" value=assignment.availableDate class="input-group mb-3"
Looks okay according to https://handlebarsjs.com/guide/partials.html#basic-partials

2020-10-29 04:24 UTC, DanielRieckhof approved these changes

2020-10-29 10:35 UTC, ABialoskorski approved these changes

2020-11-02 07:33 UTC, merged