change file permission naming
hpi-schul-cloud/schulcloud-client pull request #2292
Opened 2020-10-26 12:49 UTC by MartinSchuhmacher

# Description

Change the file permission name "Mitglied" to "Teilnehmer" in teams and remove ":innen" from "Teilnehmer:innen" in team overview.

## Links to Tickets or other pull requests

https://ticketsystem.hpi-schul-cloud.org/browse/SC-7084
## Changes

- change link to "Teilnehmer" instead of "Mitglied"
- remove ":innen" from "Teilnehmer:innen" for teams in library
## Data Security <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

No data security topics
## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review
- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-10-26 13:15 UTC, janrenz approved these changes

2020-10-27 10:01 UTC, pkleybolte approved these changes

2020-10-27 10:03 UTC, CordlessWool requested changes
Please be sure if it means the same and if we want it to relates the role name, otherwise you should change the entry for the member role.
Also remove the role if not use at an other place if not needed

2020-10-27 10:05 UTC, virgilchiriac approved these changes

2020-10-27 10:29 UTC, CordlessWool approved these changes

2020-10-27 13:56 UTC, merged