async middleware error handler added (WIP)
hpi-schul-cloud/schulcloud-client pull request #2350
Opened 2020-11-20 15:49 UTC by tofixx

# Description

This PR is fixing the control flow for error handling within of async middleware functions.

## Links to Tickets or other pull requests

## Changes

## Data Security <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-11-26 17:31 UTC, virgilchiriac approved these changes

2020-11-30 08:23 UTC, CeEv requested changes

2020-11-30 08:23 UTC, CeEv commented on controllers/alerts.js
> +router.get('/', asyncWrapper(async (req, res, next) => {
I prefer the old solution without wrapper and added catch with different handler for set feature flag and without. At the moment the wrapper is not needed at this place.

2020-11-30 08:23 UTC, CeEv commented on middleware/asyncMiddlewareWrapper.js
> +module.exports = (middlewareFunction) => function asyncWrapper(...args) {
At the moment we have no place where it is needed, but any async handler include 3 arguments req, res, next. I see no reason for make the code more complicated than it needs to be.
The second point that we should discuss is, if it is the solution. 
If i know that i must use this for catching errors, that i know that i must add the catch and add this. 
If i do not know it, i do not use this wrapper. 
It not prevent us for this error mistakes.

2021-07-08 14:21 UTC, closed without merging