SC-8004 add prometheus rest api metrics for client
hpi-schul-cloud/schulcloud-client pull request #2375
Opened 2020-12-02 09:26 UTC by tofixx

# Description
This PR introduces api metrics for the client which can be read by prometheus.
Static file routes are summarized.

## Links to Tickets or other pull requests

## Changes

## Data Security <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-12-03 08:08 UTC, mwolowyk-cap approved these changes

2020-12-03 08:08 UTC, mwolowyk-cap commented on helpers/prometheus.js
> +		path.startsWith('/fonts')
I would create a constant array with prefixes and iterate through it.

2020-12-09 09:08 UTC, CeEv requested changes
Can you please cherry pick this as hotfix for 25.3.0, is releated for SC-8101.

2020-12-09 14:33 UTC, tofixx commented
this has been hotfixed via https://github.com/hpi-schul-cloud/schulcloud-client/pull/2394

2020-12-09 14:33 UTC, closed without merging