SC-8053 - added spacing on homework page
hpi-schul-cloud/schulcloud-client pull request #2378
Opened 2020-12-03 15:46 UTC by danielasofrone

# Description

Added a margin top between the title of the section and the description

- https://ticketsystem.schul-cloud.org/browse/SC-8053

## Screenshots of UI changes
<img width="1187" alt="Screenshot 2020-12-03 at 14 53 54" src="https://user-images.githubusercontent.com/23704397/101052508-fbb89580-3586-11eb-8f44-9d331a2492f2.png">

## Approval for review
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-12-04 08:40 UTC, murat-merdoglu-hpi requested changes
I see the indentations were removed.

2020-12-07 14:56 UTC, murat-merdoglu-hpi approved these changes

2020-12-08 12:52 UTC, monaweitzenberg approved these changes
Looks fine! Thx

2020-12-09 09:48 UTC, Metauriel approved these changes

2020-12-09 13:17 UTC, merged