SC-8157  improve usability filters
hpi-schul-cloud/schulcloud-client pull request #2439
Opened 2021-01-20 09:20 UTC by danielasofrone

# Description

Changed the UI of the two filters on the Upload files page, and kept the functionality

## Links to Tickets or other pull requests

- https://ticketsystem.schul-cloud.org/browse/SC-8157

## Changes

in static - files - files.hbs and in static - scrips - files.js changed the type select into button for the second filter (up and down)

## Screenshots of UI changes
before:
<img width="487" alt="Screenshot 2021-01-20 at 10 16 46" src="https://user-images.githubusercontent.com/23704397/105153756-13cd7f80-5b09-11eb-8b45-227f0a11ecf7.png">

after:
<img width="424" alt="Screenshot 2021-01-20 at 10 16 52" src="https://user-images.githubusercontent.com/23704397/105153762-162fd980-5b09-11eb-8a3d-8c5b38c00107.png">

## Approval for review
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-01-20 14:17 UTC, murat-merdoglu-hpi commented on static/scripts/files.js
>  					);
Please solve the conflicts

2021-01-27 12:56 UTC, murat-merdoglu-hpi approved these changes

2021-01-28 06:07 UTC, monaweitzenberg requested changes
UX-Changes: Me as a user, I want to see the latest files first as it was before. Please add as default descending order. 
UI is everything fine

![image](https://user-images.githubusercontent.com/63390574/106097359-73461380-6137-11eb-8f6d-2d085292d1a2.png)

2021-01-29 10:59 UTC, monaweitzenberg approved these changes

2021-01-29 12:02 UTC, merged