SC-8595 follow up ticket to actualize gender language
hpi-schul-cloud/schulcloud-client pull request #2486
Opened 2021-02-18 12:24 UTC by monaweitzenberg

# Description
Follow-up ticket to actualize gender language/merge localize PR (SC-8318)
adding keys for landing pages and fixing missing gender 

## Links to Tickets or other pull requests
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8595

## Changes
adding keys for landing pages and fixing missing gender language

2021-02-19 08:22 UTC, mwolowyk-cap approved these changes
very well done!

2021-02-19 12:38 UTC, monaweitzenberg reviewed
thx fine

2021-02-23 10:45 UTC, sarahschaefer requested changes
Saw some things that need change

2021-02-23 10:45 UTC, sarahschaefer commented on controllers/administration.js
> -                            "title":"Deine Schüler sind in der Schülerliste rot?",
Ich bin mir nicht sicher ob es hier auch Schüler:innenliste heißen sollte, dazu hab ich nichts im Leitfaden gefunden.

2021-02-23 10:45 UTC, sarahschaefer commented on controllers/administration.js
>                              Bereits erfasste Schülerdaten werden beim Registrierungsprozess
Schüler:innendaten

2021-02-23 10:45 UTC, sarahschaefer commented on controllers/administration.js
> -                            "title":"Deine Schüler sind in der Schülerliste rot?",
https://www.genderleicht.de/Textlabor/doppelwort-gendern/
das gibt auch keine klare angabe...
aber vielleicht kann man einfach "Liste" sagen

2021-02-23 10:45 UTC, sarahschaefer commented on controllers/administration.js
>                              Bereits erfasste Schülerdaten werden beim Registrierungsprozess
Daten ?

2021-02-23 10:45 UTC, sarahschaefer commented on locales/de.json
> +				"teacher": "{{title}}Lehrkräfte",
"teacher" ist doch Einzahl, müsste es dann nicht Lehrkraft sein?

2021-02-23 10:45 UTC, sarahschaefer commented on locales/de.json
> +			"inAdditionWeArePlanning": "Zusätzlich planen wir die Entwicklung eines Eltern-Zugangs, über den Sie mit der Lehrkraft kommunizieren und mit dem Sie die Lernfortschritte Ihres Kindes nachvollziehe
Warum Duzen wir hier nicht, ist das eine mail an Eltern?

2021-02-23 10:45 UTC, sarahschaefer commented on theme/brb/views/authentication/home.hbs
> +					<!--Uncomment this when You will add brb Landing Page in ghost and remember about theme-blog.js-->
you / landing page- klein

2021-02-23 10:45 UTC, sarahschaefer commented on theme/brb/views/dataprivacy/text_einwilligung-dv.hbs
> -	Wir erheben Daten grundsätzlich auf Basis Deiner / Ihrer Einwilligung. Bei Nutzer*innen unter 18 Jahren wird nach § 1 der Datenschutzverordnung Schulwesen sowie des Brandenburgischen Schulgesetzes i
deiner (auf Plattform) dann aber klein/ Ihrer bei Eltern, Schulleiter:innen und potenziellen Neu-Kund:innen

2021-02-23 10:45 UTC, sarahschaefer commented on theme/brb/views/dataprivacy/text_intro.hbs
> +<p>Die {{theme.title}} schafft die technische Grundlage dafür, dass Lehrende und Schüler:innen in jedem Unterrichtsfach moderne digitale Lehr- und Lerninhalte nutzen können.</p>
Lehrkräfte, statt Lehrende

2021-02-23 10:45 UTC, sarahschaefer commented on theme/brb/views/dataprivacy/text_einwilligung-dv.hbs
> +	Wir erheben Daten grundsätzlich auf Basis Deiner / Ihrer Einwilligung. Bei Nutzer*innen unter 18 Jahren wird nach § 1 der Datenschutzverordnung Schulwesen sowie des Brandenburgischen Schulgesetzes i
Teilnehme = Teilnahme

2021-02-23 10:45 UTC, sarahschaefer commented on theme/thr/views/dataprivacy/text_intro.hbs
> +<p>Die {{theme.title}} schafft die technische Grundlage dafür, dass Lehrende und Schüler:innen in jedem Unterrichtsfach moderne digitale Lehr- und Lerninhalte nutzen können.</p>
Lehrende= Lehrkräfte

2021-02-23 10:45 UTC, sarahschaefer commented on views/dataprivacy/text_einwilligung-dv.hbs
> +	Vor diesem Hintergrund setzt die {{theme.title}} ein Einwilligungskonzept um, zu dem wir auch in enger Abstimmung mit Vertretern der Datenschutzbehörden aller Bundesländer stehen. Voraussetzungen fü
Teilnehme=Teilnahme

2021-02-23 10:45 UTC, sarahschaefer commented on views/dataprivacy/text_einwilligung-dv.hbs
> +	Bei Schülern unter 16 Jahren muss die Einwilligung durch einen erziehungsberechtigten Elternteil abgegeben werden. Nach Vollendung des 16. Lebensjahrs wird der oder die Schüler:in dann nach der eige
Schülern = Schüler:innen (gleich das 2. Wort)

2021-02-23 10:45 UTC, sarahschaefer commented on views/dataprivacy/text_helpdesk.hbs
> +<p>Die bei der Verwendung des Kontaktformulars erhobenen Daten werden nach vollständiger Bearbeitung Deiner / Ihrer Anfrage automatisch gelöscht, es sei denn, Deine / Ihre Anfrage wird noch zur Erfül
Deine / Ihre (am Ende des Satzes)
Entscheidung ob siezen oder duze? Wenn du, dann klein geschrieben

2021-02-23 10:45 UTC, sarahschaefer commented on views/dataprivacy/text_persbezogene-daten.hbs
> +	<li>Unterstützung der Schüler:innen bei der Nutzung interaktiver Materialen durch die Lehrenden;</li>
Lehrkräfte, statt Lehrenden

2021-02-23 10:45 UTC, sarahschaefer commented on views/dataprivacy/text_speicherdauer.hbs
> +<p>Das HPI berichtigt, löscht oder schränkt die Verarbeitung der vertragsgegenständlichen Daten nur nach dokumentierter Weisung der jeweils verantwortlichen Schule ein. Die Löschung von Daten auf ein
"Vereinbarungen  zwischen" - Lehrzeichen zu viel
sollte es nicht Schüler:innen-Accounts heißen?  
Nutzer:innen statt Nutzer*innen

2021-02-23 10:45 UTC, sarahschaefer commented on views/dataprivacy/text_speicherdauer.hbs
> +<p>Das HPI verpflichtet sich im Auftragsverarbeitungsvertrag gegenüber den Schulen, die Daten noch 90 Tage nach Beendigung des Auftragsverarbeitungsvertrags mit den Schulen aufzubewahren, damit die N
Nutzer:innen statt Nutzer*innen

2021-02-23 13:09 UTC, luizzaly commented on controllers/administration.js
>                              (z.B. durch Import aus Schüler-Verwaltungs-Software),
Schüler:innen-Verwaltungs-Software oder einfach Verwaltungs-Software?

2021-02-23 13:17 UTC, luizzaly commented on theme/brb/views/authentication/home.hbs
> +						<img src="https://schul-cloud-hpi.s3.hidrive.strato.com/brb/images/HPI_Schul_Cloud_Brandenburg_Schueler_2019.jpg"
Sollten wir die Namen der Dateien auch anpassen? ...Brandenburg_Schueler:innen.jpg?

2021-02-23 13:19 UTC, luizzaly commented on theme/brb/views/authentication/home.hbs
> +							<img src="https://schul-cloud-hpi.s3.hidrive.strato.com/images/partner/hpi-logo.jpg"
hier dann evtl. Partner:innen

2021-02-23 13:21 UTC, luizzaly commented on theme/brb/views/dataprivacy/text_einwilligung-dv.hbs
> +	Wir erheben Daten grundsätzlich auf Basis Deiner / Ihrer Einwilligung. Bei Nutzer*innen unter 18 Jahren wird nach § 1 der Datenschutzverordnung Schulwesen sowie des Brandenburgischen Schulgesetzes i
Vertreter:innen

2021-02-23 13:24 UTC, luizzaly commented on theme/open/views/dataprivacy/text_intro.hbs
> +<p>Die {{theme.title}} schafft die technische Grundlage dafür, dass Lehrende und Schüler:innen in jedem Unterrichtsfach moderne digitale Lehr- und Lerninhalte nutzen können.</p>
Lehrkräfte statt Lehrende?

2021-02-23 13:25 UTC, luizzaly commented on views/dataprivacy/text_einwilligung-dv.hbs
> +	Vor diesem Hintergrund setzt die {{theme.title}} ein Einwilligungskonzept um, zu dem wir auch in enger Abstimmung mit Vertretern der Datenschutzbehörden aller Bundesländer stehen. Voraussetzungen fü
Vertreter:innen

2021-02-23 13:26 UTC, luizzaly commented on views/dataprivacy/text_intro.hbs
> +<p>Die {{theme.title}} schafft die technische Grundlage dafür, dass Lehrende und Schüler:innen in jedem Unterrichtsfach moderne digitale Lehr- und Lerninhalte nutzen können. Weitere Informationen zum
Lehrkräfte statt Lehrende

2021-02-23 13:28 UTC, luizzaly reviewed
well done!

2021-02-24 08:32 UTC, monaweitzenberg commented on theme/brb/views/dataprivacy/text_einwilligung-dv.hbs
> -	Wir erheben Daten grundsätzlich auf Basis Deiner / Ihrer Einwilligung. Bei Nutzer*innen unter 18 Jahren wird nach § 1 der Datenschutzverordnung Schulwesen sowie des Brandenburgischen Schulgesetzes i
check.

2021-02-24 08:32 UTC, monaweitzenberg commented on theme/brb/views/dataprivacy/text_einwilligung-dv.hbs
> +	Wir erheben Daten grundsätzlich auf Basis Deiner / Ihrer Einwilligung. Bei Nutzer*innen unter 18 Jahren wird nach § 1 der Datenschutzverordnung Schulwesen sowie des Brandenburgischen Schulgesetzes i
check

2021-02-24 08:32 UTC, monaweitzenberg commented on theme/brb/views/dataprivacy/text_einwilligung-dv.hbs
> +	Wir erheben Daten grundsätzlich auf Basis Deiner / Ihrer Einwilligung. Bei Nutzer*innen unter 18 Jahren wird nach § 1 der Datenschutzverordnung Schulwesen sowie des Brandenburgischen Schulgesetzes i
check

2021-02-24 08:32 UTC, monaweitzenberg commented on theme/brb/views/dataprivacy/text_intro.hbs
> +<p>Die {{theme.title}} schafft die technische Grundlage dafür, dass Lehrende und Schüler:innen in jedem Unterrichtsfach moderne digitale Lehr- und Lerninhalte nutzen können.</p>
check

2021-02-24 08:32 UTC, monaweitzenberg commented on theme/open/views/dataprivacy/text_intro.hbs
> +<p>Die {{theme.title}} schafft die technische Grundlage dafür, dass Lehrende und Schüler:innen in jedem Unterrichtsfach moderne digitale Lehr- und Lerninhalte nutzen können.</p>
check

2021-02-24 08:32 UTC, monaweitzenberg commented on theme/thr/views/dataprivacy/text_intro.hbs
> +<p>Die {{theme.title}} schafft die technische Grundlage dafür, dass Lehrende und Schüler:innen in jedem Unterrichtsfach moderne digitale Lehr- und Lerninhalte nutzen können.</p>
check

2021-02-24 08:32 UTC, monaweitzenberg commented on views/dataprivacy/text_einwilligung-dv.hbs
> +	Vor diesem Hintergrund setzt die {{theme.title}} ein Einwilligungskonzept um, zu dem wir auch in enger Abstimmung mit Vertretern der Datenschutzbehörden aller Bundesländer stehen. Voraussetzungen fü
check

2021-02-24 08:32 UTC, monaweitzenberg commented on views/dataprivacy/text_einwilligung-dv.hbs
> +	Vor diesem Hintergrund setzt die {{theme.title}} ein Einwilligungskonzept um, zu dem wir auch in enger Abstimmung mit Vertretern der Datenschutzbehörden aller Bundesländer stehen. Voraussetzungen fü
check

2021-02-24 08:32 UTC, monaweitzenberg commented on views/dataprivacy/text_einwilligung-dv.hbs
> +	Bei Schülern unter 16 Jahren muss die Einwilligung durch einen erziehungsberechtigten Elternteil abgegeben werden. Nach Vollendung des 16. Lebensjahrs wird der oder die Schüler:in dann nach der eige
check

2021-02-24 08:32 UTC, monaweitzenberg commented on views/dataprivacy/text_helpdesk.hbs
> +<p>Die bei der Verwendung des Kontaktformulars erhobenen Daten werden nach vollständiger Bearbeitung Deiner / Ihrer Anfrage automatisch gelöscht, es sei denn, Deine / Ihre Anfrage wird noch zur Erfül
check

2021-02-24 08:32 UTC, monaweitzenberg commented on views/dataprivacy/text_intro.hbs
> +<p>Die {{theme.title}} schafft die technische Grundlage dafür, dass Lehrende und Schüler:innen in jedem Unterrichtsfach moderne digitale Lehr- und Lerninhalte nutzen können. Weitere Informationen zum
check

2021-02-24 08:32 UTC, monaweitzenberg commented on views/dataprivacy/text_persbezogene-daten.hbs
> +	<li>Unterstützung der Schüler:innen bei der Nutzung interaktiver Materialen durch die Lehrenden;</li>
check

2021-02-24 08:32 UTC, monaweitzenberg commented on views/dataprivacy/text_speicherdauer.hbs
> +<p>Das HPI verpflichtet sich im Auftragsverarbeitungsvertrag gegenüber den Schulen, die Daten noch 90 Tage nach Beendigung des Auftragsverarbeitungsvertrags mit den Schulen aufzubewahren, damit die N
check

2021-02-24 08:32 UTC, monaweitzenberg commented on controllers/administration.js
>                              Bereits erfasste Schülerdaten werden beim Registrierungsprozess
????

2021-02-24 08:32 UTC, monaweitzenberg commented on theme/brb/views/authentication/home.hbs
> +						<img src="https://schul-cloud-hpi.s3.hidrive.strato.com/brb/images/HPI_Schul_Cloud_Brandenburg_Schueler_2019.jpg"
????

2021-02-24 08:32 UTC, monaweitzenberg commented on theme/brb/views/authentication/home.hbs
> +							<img src="https://schul-cloud-hpi.s3.hidrive.strato.com/images/partner/hpi-logo.jpg"
???

2021-02-24 08:32 UTC, monaweitzenberg commented on views/dataprivacy/text_speicherdauer.hbs
> +<p>Das HPI berichtigt, löscht oder schränkt die Verarbeitung der vertragsgegenständlichen Daten nur nach dokumentierter Weisung der jeweils verantwortlichen Schule ein. Die Löschung von Daten auf ein
check
BUT Schüler-Accounts=Nutzer-Accounts (same like Nutzer-ID), right?

2021-02-24 10:23 UTC, sarahschaefer requested changes

2021-02-24 10:23 UTC, sarahschaefer commented on theme/n21/views/dataprivacy/privacy_newsletter.hbs
> +<p>Nutzer mit der Rolle „Admin“ werden während der Teilnahme im Projekt seitens des HPI über Release-Änderungen, Fehlermeldungen und sonstige projektrelevante Informationen benachrichtigt. Die Inform
Nutzer:innen

2021-02-24 12:50 UTC, sarahschaefer requested changes

2021-02-24 12:50 UTC, sarahschaefer commented on theme/n21/views/dataprivacy/privacy_rechte.hbs
> +<p>Sofern Sie registrierte/r Nutzer:innen der Niedersächsischen Bildungscloud sind, wenden Sie sich bitte an Ihre Schule. Sind sie noch kein Nutzer, richten Sie Ihre Anfrage bitte per Email oder Post
Sofern du registrierte/r Nutzer:in der ....bist.

2021-02-24 12:50 UTC, sarahschaefer commented on locales/de.json
> +					"classUsers": "Nutzer:in der Klasse",
"classUsers" sind mehrzahl ... also Nutzer:innen

2021-02-24 12:50 UTC, sarahschaefer commented on locales/de.json
> +				"editUsers": "Nutzer:in bearbeiten",
hier auch mehrzahl "Nutzer:innen"

2021-02-24 12:50 UTC, sarahschaefer commented on locales/de.json
> +				"areYouSureYouWantToDeleteTheFollowingUser": "Bist du sicher, dass du den Nutzer:in löschen möchtest?"
den/die Nutzer:in

2021-02-24 12:50 UTC, sarahschaefer commented on locales/de.json
> +				"fullPathClassUsers": "Nutzer:in der Klasse mit vollem Pfad",
mehrzahl

2021-02-24 12:50 UTC, sarahschaefer commented on locales/de.json
> +				"noSchoolCloudTitle": "Dies ermöglicht es Ihnen, dass Nutzer:in aus Ihrem LDAP nicht in die HPI Schul-Cloud übertragen werden",
Mehrzahl Nutzer:innen

2021-02-24 12:50 UTC, sarahschaefer commented on locales/de.json
> +				"anyChangesToTheFollowingConfiguration": "Jegliche Änderungen an der folgenden Konfiguration kann zur Folge haben, dass der Login für Sie und alle Nutzer:innen Ihrer Schule nicht mehr funktionier
hier wird gesiezt, wir wollen aber duzen

2021-02-24 12:50 UTC, sarahschaefer commented on locales/de.json
> +				"alternativeRegistration": "Alternativ kannst du auch im \"Nutzer:in bearbeiten\"-Dialog jedes Nutzers einzeln individuelle Registrierungslinks generieren.",
"alle Nutzer:innen einzeln" statt "jedes Nutzers einzeln"

2021-02-24 12:50 UTC, sarahschaefer commented on locales/de.json
> +				"alreadyRegistered": "Diese/r Nutzer:in ist bereits registriert",
Diese könntest du streichen, dann kann man sich den slash sparen

2021-02-24 12:50 UTC, sarahschaefer commented on locales/de.json
> +			"registrationInvalidAlreadyUsed": "Dieser/e Nutzer:in dem dieser Registrierungslink gehört, hat sich bzw. wurde bereits registriert.",
Diese/r statt Dieser/e

2021-02-24 13:50 UTC, sarahschaefer approved these changes

2021-02-24 17:18 UTC, merged