SC-9192 Fix path mapping
hpi-schul-cloud/schulcloud-client pull request #2619
Opened 2021-07-21 08:08 UTC by uidp

# Description
SC-9192 Fix path mapping

## Links to Tickets or other pull requests

## Changes

## Data Security <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-07-21 08:40 UTC, tofixx approved these changes

2021-07-27 13:43 UTC, tofixx submitted a review, later dismissed

2021-08-10 14:56 UTC, tofixx submitted a review, later dismissed

2021-08-13 07:46 UTC, virgilchiriac approved these changes

2021-08-13 09:43 UTC, mamutmk5 requested changes
It is possible to solve the _v1_ part without a breaking change?

2021-08-16 07:23 UTC, mamutmk5 approved these changes

2021-08-16 07:53 UTC, merged