Feature/bc 94 color clean up
hpi-schul-cloud/schulcloud-client pull request #2666
Opened 2021-09-03 06:19 UTC by monaweitzenberg

# Description
clean up the colors in the old client and nuxt and fixing small UX issues

## Links to Tickets or other pull requests
https://ticketsystem.hpi-schul-cloud.org/browse/BC-94

## Changes
cleaning primary, secondary and  accent color; delete tertiary color

## Screenshots of UI changes
<img width="1224" alt="open" src="https://user-images.githubusercontent.com/63390574/131959184-383baf19-0b75-
<img width="1224" alt="open" src="https://user-images.githubusercontent.com/63390574/131959294-cdc0649d-9832-425d-b750-c8a4ec03a360.png">
<img width="1222" alt="default" src="https://user-images.githubusercontent.com/63390574/131959297-3b68b05e-392a-43fa-ac3a-401d1640c629.png">
<img width="1221" alt="thr" src="https://user-images.githubusercontent.com/63390574/131959300-6a394032-859f-45dd-a525-94d83f5da807.png">
<img width="1220" alt="brb" src="https://user-images.githubusercontent.com/63390574/131959302-157b4239-9bf8-4d1f-a9ee-2b09157db613.png">
<img width="1221" alt="nbc" src="https://user-images.githubusercontent.com/63390574/131959305-e6e13261-a132-49d0-b840-931d0d4b63fb.png">

## Approval for review

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-09-03 09:33 UTC, pkleybolte requested changes

2021-09-03 09:33 UTC, pkleybolte commented on theme/n21/style.scss
> +.section-imprint.loggedout ul {
Does this belong here?

2021-09-06 10:52 UTC, monaweitzenberg commented on static/styles/courses/course.scss
> +		// color: $primaryColor;
I removed the line.

2021-09-07 07:15 UTC, luizzaly submitted a review, later dismissed
Looks good! 👍🏼

2021-09-07 13:13 UTC, pkleybolte approved these changes

2021-09-09 06:42 UTC, pkleybolte approved these changes

2021-09-10 08:10 UTC, merged