BC-651 use reusable workflows for auto deployment
hpi-schul-cloud/schulcloud-client pull request #2713
Opened 2021-11-10 15:19 UTC by alriese

# Description

## Links to Tickets or other pull requests

## Changes

## Data Security <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-11-10 16:30 UTC, mamutmk5 requested changes

2021-11-10 16:30 UTC, mamutmk5 commented on .github/workflows/clean.yml
> +  deploy:
Cleane is an better name then deploy
```suggestion
  cleane:
```

2021-11-10 16:30 UTC, mamutmk5 commented on .github/workflows/push.yml
> +         echo "IMAGE_EXISTS=$(docker manifest inspect ghcr.io/${{ github.repository }}:${{ github.sha }} > /dev/null && echo 1 || echo 0)" >> $GITHUB_ENV
also the tennens must be included in the name
```suggestion
         echo "IMAGE_EXISTS=$(docker manifest inspect ghcr.io/${{ github.repository }}-${{ matrix.tennens }}:${{ github.sha }} > /dev/null && echo 1 || echo 0)" >> $GITHUB_ENV
```

2021-11-12 09:58 UTC, mamutmk5 requested changes

2021-11-12 09:58 UTC, mamutmk5 commented on CHANGELOG.md
> +-   BC-589 - BC-651 - Change auto deployment to a reusable workflow
Move this line to his new home, it's not the release 26.16.0

2021-11-12 14:24 UTC, virgilchiriac approved these changes

2021-11-15 10:56 UTC, mamutmk5 approved these changes

2021-11-15 13:04 UTC, merged