Feature/bc 643 hide old task overview
hpi-schul-cloud/schulcloud-client pull request #2733
Opened 2021-12-09 15:12 UTC by odalys-dataport

# Description

## Links to Tickets or other pull requests

## Changes

## Data Security <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-12-15 08:46 UTC, CeEv requested changes

2021-12-15 08:46 UTC, CeEv commented on helpers/handlebars/middleware.js
> +	const homeworkRegex = new RegExp('^/homework\/*', 'i');
linter comments

2021-12-15 08:46 UTC, CeEv commented on test/mocha/homework/homework.test.js
> +				expect(res.text).to.contain(i18next.t('global.headline.assignedTasks'));	// remove language key, when everything is removed
Is it not removed?

2021-12-15 08:47 UTC, CeEv requested changes

2021-12-15 08:47 UTC, CeEv commented on test/mocha/homework/homework.test.js
> +	// TODO - delete this?
TODO

2021-12-17 14:05 UTC, uidp approved these changes

2021-12-17 14:44 UTC, merged