Feature/n21 32 new login GUI
hpi-schul-cloud/schulcloud-client pull request #2778
Opened 2022-03-10 12:01 UTC by mrikallab

# Description
NBC login GUI

## Links to Tickets or other pull requests
https://ticketsystem.hpi-schul-cloud.org/browse/N21-32

## Changes

## Data Security <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes
![3Btn](https://user-images.githubusercontent.com/93978883/157661103-e46f6e36-d508-487c-9720-e79fbbea874b.PNG)
![emailForm](https://user-images.githubusercontent.com/93978883/157662158-d83447ca-b9cf-481e-aba7-a24eb289d89a.PNG)
![ldapForm](https://user-images.githubusercontent.com/93978883/157662175-3db743e7-8657-4665-be21-e72414aa1cb2.PNG)

## Approval for review

- [x] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2022-03-18 09:42 UTC, Metauriel approved these changes

2022-03-18 11:21 UTC, Metauriel approved these changes

2022-04-14 12:03 UTC, mamutmk5 requested changes
missing the translation for ukraine

2022-04-19 08:20 UTC, mamutmk5 approved these changes

2022-04-19 08:21 UTC, merged