BC-1614 Rename env-var for student-visibilty-toggle
hpi-schul-cloud/schulcloud-client pull request #2829
Opened 2022-04-14 12:26 UTC by dyedwiper

# Description

## Links to Tickets or other pull requests

## Changes

## Data Security <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2022-04-20 12:39 UTC, CeEv requested changes

2022-04-21 09:58 UTC, dyedwiper commented on views/administration/school.hbs
> +                        {{#ifConfig "TEACHER_STUDENT_VISIBILITY__IS_CONFIGURABLE" true}}
It works just as before: If visibility is not configurable, the toggle is not rendered.

2022-04-27 09:51 UTC, odalys-dataport approved these changes

2022-05-03 07:44 UTC, CeEv approved these changes

2022-05-03 07:55 UTC, merged