BC-1500 - create upload field in handlebars
hpi-schul-cloud/schulcloud-client pull request #2866
Opened 2022-05-18 15:28 UTC by SevenWaysDP

# Description

## Links to Tickets or other pull requests

## Changes

## Data Security <sub><sup>details [on Confluence](https://docs.dbildungscloud.de/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.dbildungscloud.de/pages/viewpage.action?pageId=92831762)

2022-05-20 09:29 UTC, CeEv requested changes

2022-05-20 09:29 UTC, CeEv commented on static/scripts/files-storage.js
> +					url: `/api/v3/file/upload/
We have often /api/v3/file/ in code maybe it can put to one place on top.

2022-05-20 09:29 UTC, CeEv commented on static/scripts/files-storage.js
> +	$('#files-storage-component').find('button[data-method="delete"]').on('click', deleteFileClickHandler);
Sometimes we use .click( and somethimes on('click',  ..i think the second is the newer version without waring or?
Then we should use only this without warning.

2022-05-20 09:29 UTC, CeEv commented on static/scripts/files-storage.js
> +		e.stopPropagation();
I google stopPropagation but i have not idea if it is needed on all points or not.
Maybe it make sense. :D

2022-05-20 09:29 UTC, CeEv commented on views/files-storage/files.hbs
> +{{/extend}}
linter line break

2022-05-20 09:29 UTC, CeEv commented on views/files-storage/files.hbs
> +    {{#content "scripts" mode="append"}}
Not sure with the css files, but for js files i think it should work to put it into the embedded hbs file and it should work. For html + js it self it is no problem to but js file loads into body, or we can do it to fileStorageImports.hbs like imprts.hbs file.

2022-05-20 09:29 UTC, CeEv commented on views/lib/components/files-storage/file-upload.hbs
> +                        <span class="percent" role="progressbar" aria-valuemin="0" aria-valuemax="100"></span>
Push ..they want something more. :P

2022-05-20 09:29 UTC, CeEv commented on views/lib/components/files-storage/files-grid.hbs
> +							{{#ifneq this.securityCheck.status "blocked"}} fileviewer{{/ifneq}}"
Can we put it togehter in one {{#ifneq this.securityCheck.status "blocked"}} ?

2022-05-20 09:29 UTC, CeEv commented on views/lib/components/files-storage/files-grid.hbs
> +								{{#userHasPermission "FILE_DELETE"}}
If we use in backend FILE_STORAGE_* then we should also replace each of the outdated permissions.
We should also check if the vue client use the rights.

2022-05-20 09:29 UTC, CeEv commented on views/lib/components/files-storage/files.hbs
> +</div>
line break

2022-05-20 09:29 UTC, CeEv commented on views/lib/components/files-storage/forms/form-name-edit.hbs
> +</div>
line break

2022-05-20 09:29 UTC, CeEv commented on views/lib/components/files-storage/files-grid.hbs
> +{{#embed "lib/components/modal-form" class="rename-modal"}}
The file combine different embed but the section are is added directly. 
We should outsource it too, or put the others also to the file without embed.

2022-05-20 09:37 UTC, SevenWaysDP commented on config/default.schema.json
> +					"default": "http://localhost:4444",
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/261

2022-05-20 10:40 UTC, SevenWaysDP commented on static/scripts/files-storage.js
> +			.unbind('click')
remove click event handler from element

2022-05-24 07:37 UTC, CeEv commented
Todo: Test files with size > 750 MB and with self added data types.

2022-05-30 08:50 UTC, odalys-dataport requested changes

2022-05-30 08:50 UTC, odalys-dataport commented on locales/de.json
> +				"fileNotFound": "Die Datei nicht gefunden",
"Die Datei konnte nicht gefunden werden"

2022-05-30 08:50 UTC, odalys-dataport commented on locales/de.json
> +			"storeFilesForUploadProgress": "Dateien werden Hochladen.",
"Dateien werden hochgeladen"

2022-05-30 08:50 UTC, odalys-dataport commented on locales/de.json
> +			"storeFilesForUploadDisabled": "Dateien zum Hochladen kann nur nach erste speichern erfolgen.",
Was? :D
Vielleicht: "Dateien können nur nach dem ersten Speichern hochgeladen werden"

2022-05-30 08:59 UTC, odalys-dataport requested changes

2022-05-30 08:59 UTC, odalys-dataport commented on locales/de.json
>  		}
What about the other language files?

2022-05-30 08:59 UTC, odalys-dataport commented on controllers/topics.js
>  	const context = req.originalUrl.split('/')[1];
There is a save without formatting function in visual studio code :P

2022-05-30 19:14 UTC, odalys-dataport approved these changes

2022-05-31 12:47 UTC, CeEv approved these changes

2022-06-01 08:22 UTC, merged