BC-2521 trigger valididation on password confirmation input
hpi-schul-cloud/schulcloud-client pull request #2986
Opened 2022-10-13 08:50 UTC by pkleybolte

# Description

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/BC-2521

## Changes

## Data Security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2022-10-17 13:24 UTC, psachmann requested changes
Walked through the steps mentioned in the Jira-Ticket and still get no hint/notification when the provided passwords are different.

2022-10-17 15:10 UTC, pkleybolte commented
> Walked through the steps mentioned in the Jira-Ticket and still get no hint/notification when the provided passwords are different.

Works for me in Chrome, Firefox and mobile Chrome. What browser did you use?

2022-10-18 14:32 UTC, HeftyTea approved these changes
Functionally review OK. Created teacher, created invitation link, tested password (mis)-match OK. Blocked on client side OK. 
Technical review OK. (see question regarding event.

2022-10-18 14:32 UTC, HeftyTea commented on static/scripts/dataprivacy/user-registration.js
> +	if (passwordConfirmInput) passwordConfirmInput.onkeyup = validatePassword;
What was the reason to go with onchange, and onkeyup here? Is oninput an option in both cases?

2022-10-20 07:17 UTC, psachmann approved these changes

2022-10-20 07:18 UTC, merged