BC-1033 amp char not displayed properly in a course name field
hpi-schul-cloud/schulcloud-client pull request #3015
Opened 2022-11-21 09:57 UTC by bn-pass

# Description

## Links to Tickets or other pull requests

https://ticketsystem.dbildungscloud.de/browse/BC-1033

## Changes

Add decoding of the course name retrieved from the BE as it was not properly displayed in an input field.

## Data Security

## Deployment

No new deployment requirements

## New Repos, NPM packages or vendor scripts

Added new package called he (https://www.npmjs.com/package/he) - it's a small package without any dependencies that help to e.g. properly decode values as they would be by the browser - useful if this type of decoding should be done on the server side as in this case.

## Screenshots of UI changes

No UI changes, just the behavioural change of adding proper decoding of the data displayed in an input form.

## Approval for review

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2022-11-22 15:01 UTC, uidp requested changes
We should not decode the html entities in the controller. Instead we should use the "triple-slash" syntax in the template to render the course name (see also `views/homework/edit.hbs`):

```diff
--- a/views/courses/edit-course.hbs
+++ b/views/courses/edit-course.hbs
@@ -81,7 +81,7 @@

                                <div class="form-group">
                                        <label for="mathsClass">{{$t "global.label.nameOfTheCourse"}}</label>
-                                       <input id="mathsClass" class="form-control" name="name" type="text" placeholder="{{$t "courses.global.input.mathsClass"}}" value="{{course.name}}"
+                                       <input id="mathsClass" class="form-control" name="name" type="text" placeholder="{{$t "courses.global.input.mathsClass"}}" value="{{{course.name}}}"
                                                {{#if course.isArchived}}disabled{{/if}} required autofocus />
                                </div>
```

See also [https://handlebarsjs.com/guide/#html-escaping](https://handlebarsjs.com/guide/#html-escaping)

2022-11-22 15:24 UTC, bn-pass commented
> We should not decode the html entities in the controller. Instead we should use the "triple-slash" syntax in the template to render the course name (see also `views/homework/edit.hbs`):
> 
> ```diff
> --- a/views/courses/edit-course.hbs
> +++ b/views/courses/edit-course.hbs
> @@ -81,7 +81,7 @@
> 
>                                 <div class="form-group">
>                                         <label for="mathsClass">{{$t "global.label.nameOfTheCourse"}}</label>
> -                                       <input id="mathsClass" class="form-control" name="name" type="text" placeholder="{{$t "courses.global.input.mathsClass"}}" value="{{course.name}}"
> +                                       <input id="mathsClass" class="form-control" name="name" type="text" placeholder="{{$t "courses.global.input.mathsClass"}}" value="{{{course.name}}}"
>                                                 {{#if course.isArchived}}disabled{{/if}} required autofocus />
>                                 </div>
> ```
> 
> See also https://handlebarsjs.com/guide/#html-escaping

Ok thanks, will change my solution then. I assume the reason behind your solution is that  it's just simpler and does not require any additional JS calls in our code right?

2022-11-23 07:45 UTC, uidp reviewed
Sorry I made a mistake. If we use "triple-stash" syntax in the template we get raw output of the string which can lead to security issues. So I guess your solution was correct. We should also change that in the task edit page controller and template:
https://github.com/hpi-schul-cloud/schulcloud-client/blob/0efa03b72602d92ee4a5f7f7f6f302e9316dc627/controllers/homework.js#L535

2022-11-23 09:22 UTC, uidp approved these changes

2022-11-23 10:05 UTC, merged