Bc 1506 switch handling of submission files
hpi-schul-cloud/schulcloud-client pull request #3039
Opened 2022-12-13 08:34 UTC by SevenWaysDP

# Description

## Links to Tickets or other pull requests

## Changes

## Data Security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2022-12-13 13:19 UTC, CeEv requested changes

2022-12-13 13:19 UTC, CeEv commented on helpers/homework.js
>  function getGradingFileName(file) {
The function is still alive for backward compatibility? 
Sound like a seach all used place and replace it with file.name.

2022-12-13 13:19 UTC, CeEv commented on helpers/homework.js
> +	return `/api/v3/file/download/${file.id}/${encodeURIComponent(file.name)}`;
get**Grading**FileDownloadPath ..should we not only touch the submitted files? 
Is the naming of the function wrong?

2022-12-13 13:19 UTC, CeEv commented on views/lib/components/files-storage/imports.hbs
>  {{/content}}
The github linter want a line break.

2022-12-14 08:08 UTC, bischofmax commented on views/homework/submission.hbs
>          <div class="form-group">
Hier fehlt noch folgende Infobox: "Dateien können erst nach dem ersten Speichern einer Abgabe hochgeladen werden."

2022-12-14 08:13 UTC, bischofmax commented on views/homework/submission.hbs
> +            <button type="submit" class="btn btn-primary btn-submit" data-testid="tasks-submission-save-and-send-btn">{{$t "homework.button.save" }}</button>
Nach einem File Upload wird kein Reload ausgefüht.

2022-12-15 09:01 UTC, bischofmax commented on views/homework/submission.hbs
> +                {{$t "topic.topicEdit.label.uploadAfterFirstSave"}}
Hier braucht es noch eine spezifische Übersetzung für die Abgabe. Im Task wird diese auch fälschlicherweise verwendet.

2022-12-15 11:02 UTC, bischofmax commented on views/homework/submission.hbs
> +                {{$t "topic.topicEdit.label.uploadAfterFirstSave"}}
Die generische Variante: Dateien können erst nach dem ersten Speichern hochgeladen werden.

2022-12-15 13:40 UTC, bischofmax approved these changes

2022-12-19 13:27 UTC, bischofmax approved these changes

2022-12-19 15:38 UTC, merged