BC-3134 Add files info in user delete form teams.
hpi-schul-cloud/schulcloud-client pull request #3099
Opened 2023-02-10 20:29 UTC by blazejpass

# Description

Adding information about user's assigned files while removing user form team.

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/BC-3134

## Changes

## Data Security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-02-15 11:43 UTC, VicDavydiuk commented on controllers/teams.js
> +		team.userIds.map((user) => {
map always returns value, that we don't use here, use forEach for cases where we don't need transformed array.

2023-02-16 08:30 UTC, VicDavydiuk approved these changes

2023-02-16 11:54 UTC, SevenWaysDP requested changes

2023-02-16 11:54 UTC, SevenWaysDP commented on controllers/teams.js
> +		}
You can set let files = [] and set logger.warn(files); into catch and remove this if statment

2023-02-17 08:43 UTC, SevenWaysDP approved these changes

2023-02-21 08:39 UTC, merged