Added css rules to add status event in n21 mobile version.
hpi-schul-cloud/schulcloud-client pull request #3226
Opened 2023-07-11 14:53 UTC by Michaellinaresxk

# Description

## Links to Tickets or other pull requests

## Changes

## Data Security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-07-14 10:00 UTC, VikDavydiuk reviewed
![photo_2023-07-14_11-52-15](https://github.com/hpi-schul-cloud/schulcloud-client/assets/117301540/022ec31b-08fd-4532-a61e-6d9aeeb8d3ab)
![photo_2023-07-14_11-52-15 (2)](https://github.com/hpi-schul-cloud/schulcloud-client/assets/117301540/238e2525-d369-4a30-bc5a-6d1eba43cb2b)
![photo_2023-07-14_11-52-15 (3)](https://github.com/hpi-schul-cloud/schulcloud-client/assets/117301540/31628aaf-ea0a-40c8-86b3-ffa398fe5704)
![photo_2023-07-14_11-52-15 (4)](https://github.com/hpi-schul-cloud/schulcloud-client/assets/117301540/f20be695-e576-47d9-9f81-c50834e13bab)
![photo_2023-07-14_11-52-15 (5)](https://github.com/hpi-schul-cloud/schulcloud-client/assets/117301540/a7c36e3d-d182-4d14-8b59-49f36b023a6a)
![photo_2023-07-14_11-52-15 (6)](https://github.com/hpi-schul-cloud/schulcloud-client/assets/117301540/6380eb8a-520c-41ba-9700-ededcb3e6235)
![photo_2023-07-14_11-52-15 (7)](https://github.com/hpi-schul-cloud/schulcloud-client/assets/117301540/89e2a186-0de2-41ff-8de7-6b8c79eb29f5)
![photo_2023-07-14_11-52-15 (8)](https://github.com/hpi-schul-cloud/schulcloud-client/assets/117301540/d53d0ec3-716e-4d0d-bba8-81703d65f568)
![photo_2023-07-14_11-52-15 (9)](https://github.com/hpi-schul-cloud/schulcloud-client/assets/117301540/9492c456-56dd-417f-b761-31586e3b28c7)
This is how it shows up on my phone (OnePlus Nord N10 5G)

2023-07-17 07:01 UTC, sszafGCA commented on config/global.js
> +	SC_THEME = 'n21',
do not change theme

2023-07-17 07:01 UTC, sszafGCA commented on gulpfile.js
> +	return process.env.SC_THEME || 'n21';
Same here

2023-07-17 07:10 UTC, sszafGCA commented
As BC-3743 is done as a part of this story I left the comments on some scss files to do refactor of code. Please look at those comment:
//TODO in BC-3743

2023-07-21 11:35 UTC, VikDavydiuk commented on static/styles/lib/alerts.scss
> +					left: 285px;
You use rem, em, px. Can we use one of them? Also, avoid magic numbers

2023-07-23 19:26 UTC, MartinSchuhmacher requested changes

2023-07-23 19:26 UTC, MartinSchuhmacher commented on static/styles/lib/alerts.scss
> +			margin-top: -0.5em;
can we avoid using negative values at all here?

2023-07-23 19:26 UTC, MartinSchuhmacher commented on static/styles/lib/alerts.scss
> +					left: 17.8em;
why overwriting a fixed px value with em value? makes it hard to find issues later

2023-07-23 19:26 UTC, MartinSchuhmacher commented on static/styles/lib/header.scss
> +		margin-top: 3px;
same here, as the more specificated values follow rem values, I would not like to have different units as base

2023-07-23 19:26 UTC, MartinSchuhmacher commented on static/styles/lib/loggedin.scss
> +	margin: -5px 0.25rem 0 0;
dont mix px and rem within one element

2023-07-23 19:26 UTC, MartinSchuhmacher commented on static/styles/lib/loggedin.scss
> +		height: 50px;
see above about mixing

2023-07-23 19:26 UTC, MartinSchuhmacher commented on static/styles/lib/loggedin.scss
> +		width: 9.375em;  /* (150px / 16px) */
is the calculation important for something? if it is, then put the origin values into variables and calculate the value here based on them. if not: remove the comment

2023-07-23 19:26 UTC, MartinSchuhmacher commented on theme/brb/style.scss
> +                    width: 13rem !important;
differentiate between parent and root element in styling one specific element does not sound like a good idea

2023-07-23 19:26 UTC, MartinSchuhmacher commented on theme/brb/style.scss
> +                    height: 50px;
see above (mixing)

2023-07-23 19:26 UTC, MartinSchuhmacher commented on theme/default/style.scss
> +                height: 2rem;
see above (parent vs root)

2023-07-23 19:26 UTC, MartinSchuhmacher commented on theme/n21/style.scss
> +                    height: 2rem;
see above

2023-07-23 19:26 UTC, MartinSchuhmacher commented on theme/thr/style.scss
> +                    height: 2rem;
see above

2023-07-25 10:57 UTC, MartinSchuhmacher approved these changes

2023-07-26 07:21 UTC, VikDavydiuk reviewed
![image](https://github.com/hpi-schul-cloud/schulcloud-client/assets/117301540/29b52e97-5a51-43be-92a0-b08a676117b1)
![image](https://github.com/hpi-schul-cloud/schulcloud-client/assets/117301540/ac7e916e-6caa-4f85-ad92-8c0478f5c704)

2023-07-26 07:30 UTC, VikDavydiuk approved these changes

2023-07-26 13:06 UTC, merged