Added functionality to display & character instead of &amp on theme c…
hpi-schul-cloud/schulcloud-client pull request #3291
Opened 2023-08-29 12:27 UTC by Michaellinaresxk

<img width="1512" alt="Screen Shot 2023-08-29 at 2 17 54 PM" src="https://github.com/hpi-schul-cloud/schulcloud-client/assets/116801315/37191fe0-658a-4ae7-a372-eb93c47e8e48">
…reation.

# Description

## Links to Tickets or other pull requests

## Changes

## Data Security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-08-29 13:29 UTC, bn-pass requested changes
I know the ticket's description only mentions the & character, but in my opinion the solution is too limited - please try to use some generic function to properly decode any possible special characters. Maybe you can use a similar [solution like for the BC-1033 ticket](https://github.com/hpi-schul-cloud/schulcloud-client/pull/3015/files) as the issue seems to be exactly the same.

2023-08-29 22:09 UTC, bn-pass requested changes
It's better now, but please do this check-and-decode for each field separately - in this solution if, e.g., course description would be undefined, the course name would not be properly decoded. So just do it the same way, but for every field separately.

2023-08-30 07:55 UTC, bn-pass approved these changes

2023-08-30 08:16 UTC, odalys-dataport approved these changes

2023-09-14 07:44 UTC, odalys-dataport approved these changes

2023-09-14 07:45 UTC, SevenWaysDP approved these changes

2023-09-14 10:40 UTC, merged