N21-1206 show classes and goups
hpi-schul-cloud/schulcloud-client pull request #3305
Opened 2023-09-15 12:09 UTC by MarvinOehlerkingCap

# Description
- add new sidebar item

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/N21-1206
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4406
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/643

## Changes

## Data Security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-09-19 14:37 UTC, IgorCapCoder approved these changes

2023-09-21 07:45 UTC, arnegns approved these changes

2023-09-21 07:45 UTC, arnegns commented on locales/de.json
> +				"administrationClassesNew": "Klassen (neu)",
Something for BB. We need a ticket to remove the "(neu)"

2023-09-21 08:11 UTC, arnegns requested changes

2023-09-21 08:11 UTC, arnegns commented on helpers/handlebars/middleware.js
> +	const newClassViewEnabled = FEATURE_SHOW_NEW_CLASS_VIEW_ENABLED === 'true';
What is the requirement? Actually we only show this menu if we click on a menu item with sub items.
On the "Verwaltung" page we cant see the new menu: https://nbc-n21-1206-show-classes-and-goups.cd.dbildungscloud.dev/administration

2023-09-22 07:57 UTC, arnegns approved these changes

2023-09-27 13:47 UTC, merged