N21-1774 create synced course
hpi-schul-cloud/schulcloud-client pull request #3426
Opened 2024-03-15 11:35 UTC by MBergCap

# Description

## Links to Tickets or other pull requests

https://ticketsystem.dbildungscloud.de/browse/N21-1774

## Changes

## Data Security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-03-19 10:37 UTC, arnegns requested changes

2024-03-19 10:37 UTC, arnegns commented on controllers/courses.js
> +	if (Configuration.get('FEATURE_SCHULCONNEX_COURSE_SYNC_ENABLED') && req.query.syncWithGroup) {
Please rename the variable so that we can see its an id

2024-03-27 14:35 UTC, MarvinOehlerkingCap approved these changes

2024-03-28 08:30 UTC, arnegns approved these changes

2024-04-08 14:25 UTC, merged