BC-6672 fix incorrect translation in alert
hpi-schul-cloud/schulcloud-client pull request #3427
Opened 2024-03-18 13:40 UTC by MichalNers

# Description

## Links to Tickets or other pull requests

## Changes

## Data Security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-03-19 01:00 UTC, bn-pass requested changes

2024-03-19 01:00 UTC, bn-pass commented on locales/calendar/es.json
What about files with german and english translations? I only see `es.json` and `uk.json` in `locales/calendar` dir.

2024-03-19 11:45 UTC, MichalNers commented on .prettierrc.js
right !

2024-03-19 11:49 UTC, MichalNers commented on helpers/momentHelper.js
> +	future: `${localFile['moment.relativeTime.futureIn']} %s`,
![image](https://github.com/hpi-schul-cloud/schulcloud-client/assets/159016966/92aa9d06-020c-45bd-89d9-bfdf0a91203f)
looks good

2024-03-19 11:50 UTC, MichalNers commented on locales/calendar/es.json
Moment library  has translated English and German

2024-03-20 13:21 UTC, bn-pass approved these changes

2024-03-21 08:43 UTC, CeEv approved these changes

2024-03-22 10:17 UTC, CeEv approved these changes

2024-03-22 11:17 UTC, merged